### ISSUE TITLE
[Feature Request] All button on inventory

### ISSUE THREAD

**Issue by Euchale** [Pyrdacor/Ambermoon#20]
It would be amazing to add an "all" button to any inventory interaction. Don´t know how difficult it would be to add, but currently the fastest way is to pick up whichever item you only have one of, and then drop it on a stack to pick the entire stack up fast.

An alternative might be that when you select a stack of items the default value is not 0 but the max number you currently have.
In general, shouldn´t the default value be 1?

**Comment by Pyrdacor** [comment]
You mean for drag&drop? You can pick up all items at once with the right mouse button?

For other actions when the popup for the amount is shown you can just right click on the arrow up button to select the max amount. You can also use the keys "page up" or "home" (pos1 in German).

Isn't that enough?

**Comment by Euchale** [comment]
I was completely unaware that all of those were options!  I played through half the game always manually typing in the number of items I had until I found out you can just type in a larger number for it to default to the max number.
I cannot tell why it never even crossed my mind to use the right mouse button haha.

**Comment by Pyrdacor** [comment]
There are quite some handy shortcuts for several things. The right mouse button can be used for all kind of stuff.

For example in battles you can right click a character on the playfield to open his inventory, same for right clicks on the portraits. Right clicks also switch the action buttons in the lower right area of the screen and much more.

I also plan to add some more shortcuts to the remake with Shift or Control keys. For example fast equip/unequip, fast item use and so on.

I guess I will add some documentation for all the controls to the next releases so that everybody can read what is possible.
