### ISSUE TITLE
Cpt. Torle (Spannenberg) house glitches

### ISSUE THREAD

**Issue by Hexaae** [Pyrdacor/Ambermoon#32]
Hi, today I noticed I can move outside of the map on the left at Torle's in Spannenberg:
![image](https://user-images.githubusercontent.com/8591462/166151056-574de2cb-d79e-467d-8cca-8b244f4c2cdc.png)

Moreover Cpt. Torle and his assistant will still talk about a free boat waiting "for the heros" even if you already accomplished the task... can't remember exactly (savegame was from 2001 :D).
Tested with an advanced save-game though, so maybe it has something to do with v.1.10 fix: "- Fixed ship dealer in Spannenberg. Ships will now correctly be spawned." and is simply not a retro-active fix? Should this be fixed starting a new game?

**Comment by Pyrdacor** [comment]
No this was never fixed yet. But I already know that. I have to add a blocking tile to the tiles for the first issue. For the second one I would have to add texts and conversation logic. Both is possible. It's a good candidate for the next release. It will then also work for old savegames.

**Comment by Pyrdacor** [comment]
![image](https://user-images.githubusercontent.com/8607784/168280095-6297a015-8a78-4e4f-80da-29ec78181e1f.png)

I fixed it by adding a new tile which blocks. The problem was that the piece of stairs overrides the blocking state of the lower tile which is the blocking wall. Now an additional piece of stairs was added which uses the background tile flags.

In addition I added a new tile graphic and adjusted the part above the stairs a bit. I think it looks quite strange in the original.

**Comment by Pyrdacor** [comment]
Will be part of 1.14 english and 1.13 german

**Comment by Hexaae** [comment]
Tested 1.14.
Dialogues still

**Comment by Pyrdacor** [comment]
The assistent is a simplified NPC. Those are only associated to a map text via index. So their text can't change. The only possibility would be to swap the NPC with another one which looks identical and is associated to another text.
