### ISSUE TITLE
Text bug

### ISSUE THREAD

**Issue by Pyrdacor** [Pyrdacor/Ambermoon#37]
NPC text 028.003:

"I WISH YOU WELL ON YOUR WAY AND MAY THE EAGLES OF IMMERDAR BE OUR FRIENDS!"

The word "IMMERDAR" is an old German word for "always". I guess the translator didn't know it and thought that was some kind of name.

It should be something like:

"I WISH YOU WELL ON YOUR WAY AND MAY THE EAGLES ALWAYS BE OUR FRIENDS!"

Is there some cool old word for "always" in english?

**Comment by a1exh** [comment]
Perhaps FOREVER?

**Comment by Pyrdacor** [comment]
I guess it would be ok.

**Comment by Metibor** [comment]
Hi there!
What about "...may the eagles be our everlasting friends!"

**Comment by Pyrdacor** [comment]
Sound go to me. @a1exh ?

**Comment by a1exh** [comment]
"ALWAYS" "FOREVER" or "EVERLASTING" all work. Whatever you think best.

**Comment by xenonmb** [comment]
i think the closest and best match would be "forevermore", also I don't 100% know the context, but shouldn't it be "YOUR friends" instead of "OUR friends"?
So the line would be "I WISH YOU WELL ON YOUR WAY AND MAY THE EAGLES BE YOUR FRIENDS FOREVERMORE!"

Synonyms
always, aye (also ay), e'er, eternally, ever, everlastingly, evermore, forever, indelibly, permanently, perpetually

**Comment by Pyrdacor** [comment]
I used Metibor's text now. Will be part of 1.15.
