### ISSUE TITLE
A minor wording issue related to the apparition of Shandra's spirit (English v)

### ISSUE THREAD

**Issue by macce2** [Pyrdacor/Ambermoon#86]
Shandra: " ... Great danger lies over Lyramion... and if you do not hurry,
THE TOWN will be destroyed.."

Well, not a typo per se; but I think better would be to use 
something like " the whole Lyramion" or " the whole country" 
instead of the word "THE TOWN"; 
maybe even "everything will be destroyed" ..!?

Speaking of Shandra; shouldn't the Shandra's Amber stone
stay with the coffin, after being used succesfully..?!
Currently it does remain in the user's inventory.
Is that on purpose ..?!

**Comment by Pyrdacor** [comment]
Moved to the Ambermoon repo

**Comment by Pyrdacor** [comment]
I use the AmbermoonTextManager for the original release now as well. Therefore the english (and soon the french) versions inside the Disks/Bugfixing folder will now contain a new folder "AllTexts" which contains all the texts. Bugfixing the two non-german languages will therefore only be text-related from now on and you can see this better as the text changes are non-binary as well.

The german version is the main version where all data-related bugfixes take place. There are some exceptions for now like intro, outro or maybe some boot/install scripts.

Before a new release I will use the up-to-date german version and patch it with the english and french texts to create the language releases.

This issue is the first one I fixed only in text in commit 3ea4b1ef05ed26fdd7fbc94d534a7bb8d5a16c6a.
